# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python
# and use modern dependency management
build:
  os: ubuntu-22.04
  apt_packages:
    - libmagic1
  tools:
    python: "3.10"
  jobs:
    pre_build:
      - "pip install '.[docs]'"

# Build documentation in the docs/ directory
sphinx:
  configuration: docs/conf.py