version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
      - image: cimg/postgres:13.3
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: xocto-dev
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            python -m venv /home/circleci/venv/
            echo "source /home/circleci/venv/bin/activate" >> $BASH_ENV
      - restore_cache:
          keys:
            - &cache-key python-3.9-packages-v1-{{ checksum "pyproject.toml" }}
            - &cache-key-prefix python-3.9-packages-v1-
      - run:
          name: Install dev dependencies
          command: make install
      - save_cache:
          key: *cache-key
          paths:
            - "/home/circleci/venv/"
            - "/home/circleci/.cache/pip"
      - run:
          name: Check formatting
          command: make format_check
          when: always
      - run:
          name: Check linting
          command: make lint_check
          when: always
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.6.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: make test
          when: always
      - run:
          name: Check Python type annotations
          command: make mypy
          when: always
