version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build:
    docker:
      - image: cimg/python:3.10
      - image: cimg/postgres:15.19
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: xocto-dev
    steps:
      - checkout:
          method: full
      - python/install-packages:
          pkg-manager: uv
          args: --all-groups
      - run:
          name: Check uv lock file
          command: uv lock --check
      - run:
          name: Check formatting
          command: make format_check
          when: always
      - run:
          name: Check linting
          command: make lint_check
          when: always
      - run:
          name: install dockerize
          command: |
            wget -nv https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
            sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz dockerize
            rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.15.1
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Run tests
          command: make test
          when: always
      - run:
          name: Check Python type annotations
          command: make mypy
          when: always
