version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            python -m venv /home/circleci/venv/
            echo "source /home/circleci/venv/bin/activate" >> $BASH_ENV
      - restore_cache:
          keys:
            - &cache-key python-3.9-packages-v1-{{ checksum "pyproject.toml" }}
            - &cache-key-prefix python-3.9-packages-v1-
      - run:
          name: Install dev dependencies
          command: make install
      - save_cache:
          key: *cache-key
          paths:
            - "/home/circleci/venv/"
            - "/home/circleci/.cache/pip"
      - run:
          name: Check formatting
          command: make format_check
          when: always
      - run:
          name: Check linting
          command: make lint_check
          when: always
      - run:
          name: Run tests
          command: make test
          when: always
      - run:
          name: Check Python type annotations
          command: make mypy
          when: always
