version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Install dev dependencies
          command: |
            python3 -m venv ~/venv
            . ~/venv/bin/activate
            make install
      - run:
          name: Test
          command: |
            . ~/venv/bin/activate
            make test
      - run:
          name: Lint
          command: |
            . ~/venv/bin/activate
            make lint
      - run:
          name: Mypy
          command: |
            . ~/venv/bin/activate
            make mypy
      - run:
          name: Black
          command: |
            . ~/venv/bin/activate
            make black_check
