version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.9
    steps:
      - checkout
      - run:
          name: Create virtualenv
          command: |
            python -m venv /home/circleci/venv/
            echo "source /home/circleci/venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install dev dependencies
          command: make install
      - run:
          name: Test
          command: make test
      - run:
          name: Lint
          command: make ruff
      - run:
          name: Mypy
          command: make mypy
      - run:
          name: Format
          command: make format_check
